import { PunctuationPauses } from "../../types/ui";

export type PunctuationType =
  | "period"
  | "questionExclamation"
  | "colonSemicolon"
  | "comma"
  | "ellipsis"
  | "none";

export const DEFAULT_PUNCTUATION_PAUSES: PunctuationPauses = {
  comma: 0.5,
  period: 0.5,
  questionExclamation: 1.0,
  colonSemicolon: 0.6,
};

/**
 * Detects the trailing punctuation of a sentence or chunk text.
 * Strips closing quotes, parentheses, brackets before inspecting the punctuation mark.
 */
export function detectTrailingPunctuation(text: string): PunctuationType {
  const trimmed = text.trim();
  if (!trimmed) return "none";

  // Match optional closing quotes/brackets/parentheses at the end of text
  const match = trimmed.match(/([.!?:;,…]+)["'”’»›)\]}]*$/u);
  if (!match) {
    // Also check for 3 dots "..."
    if (/\.\.\.["'”’»›)\]}]*$/u.test(trimmed)) {
      return "ellipsis";
    }
    return "none";
  }

  const punct = match[1];

  // Check ellipsis (… or ...)
  if (punct.includes("…") || punct.length >= 3) {
    return "ellipsis";
  }

  const lastChar = punct[punct.length - 1];
  if (lastChar === "." || lastChar === "。") {
    return "period";
  }
  if (lastChar === "!" || lastChar === "?" || lastChar === "！" || lastChar === "？") {
    return "questionExclamation";
  }
  if (lastChar === ":" || lastChar === ";" || lastChar === "：" || lastChar === "；") {
    return "colonSemicolon";
  }
  if (lastChar === "," || lastChar === "，" || lastChar === "、") {
    return "comma";
  }

  return "none";
}

/**
 * Calculates the target pause in milliseconds for a chunk or boundary.
 *
 * Rules:
 * 1. Punctuation is the SOLE decider of pause durations.
 * 2. If a manual pause [PAUSE {ms}] is explicitly set, it is respected.
 * 3. Paragraph breaks and line breaks DO NOT create additional pause.
 * 4. Technical chunk boundaries without punctuation produce 0 ms pause.
 */
export function getTargetPauseMs(
  text: string,
  config?: Partial<PunctuationPauses>,
  manualPauseMs?: number | "auto"
): number {
  // Explicit user manual pause override takes precedence if explicitly provided as number
  if (typeof manualPauseMs === "number" && manualPauseMs >= 0) {
    return Math.round(manualPauseMs);
  }

  const punctType = detectTrailingPunctuation(text);
  const period = config?.period ?? DEFAULT_PUNCTUATION_PAUSES.period;
  const comma = config?.comma ?? DEFAULT_PUNCTUATION_PAUSES.comma;
  const qe = config?.questionExclamation ?? DEFAULT_PUNCTUATION_PAUSES.questionExclamation;
  const cs = config?.colonSemicolon ?? DEFAULT_PUNCTUATION_PAUSES.colonSemicolon;

  switch (punctType) {
    case "period":
      return Math.round(period * 1000);
    case "questionExclamation":
      return Math.round(qe * 1000);
    case "colonSemicolon":
      return Math.round(cs * 1000);
    case "comma":
      return Math.round(comma * 1000);
    case "ellipsis":
      // Ellipsis uses period duration by default
      return Math.round(period * 1000);
    case "none":
    default:
      // Technical boundary without punctuation produces 0 ms pause
      return 0;
  }
}

/**
 * Calculates the effective silence gap to append between segments, avoiding
 * accumulating trailing silence already present in the model's generated audio.
 *
 * Example:
 * targetPauseMs = 500 ms (period)
 * existingTrailingSilenceMs = 200 ms (generated by model)
 * effectiveSilenceGapMs = max(0, 500 - 200) = 300 ms
 * Total final silence: 200ms + 300ms = 500ms (matches configuration exactly).
 */
export function calculateEffectiveSilenceGapMs(
  targetPauseMs: number,
  existingTrailingSilenceMs = 0
): number {
  const safeTarget = Math.max(0, targetPauseMs);
  const safeExisting = Math.max(0, existingTrailingSilenceMs);
  return Math.max(0, safeTarget - safeExisting);
}

/**
 * Analyzes audio samples to detect existing trailing silence in milliseconds.
 * Scans backward from the end in 10ms windows using RMS energy.
 */
export function detectTrailingSilenceMs(
  samples: Int16Array | Float32Array | number[],
  sampleRate = 44100,
  silenceThresholdRms = 0.006 // ~ -44.4 dB
): number {
  if (!samples || samples.length === 0) return 0;

  const windowSize = Math.max(1, Math.floor(sampleRate * 0.01)); // 10ms
  let silentSamples = 0;

  for (let i = samples.length - 1; i >= 0; i -= windowSize) {
    const start = Math.max(0, i - windowSize + 1);
    let sumSquares = 0;
    const count = i - start + 1;

    for (let j = start; j <= i; j++) {
      let val = samples[j];
      if (samples instanceof Int16Array) {
        val = val / 32768;
      }
      sumSquares += val * val;
    }

    const rms = Math.sqrt(sumSquares / count);
    if (rms < silenceThresholdRms) {
      silentSamples += count;
    } else {
      break;
    }
  }

  return Math.round((silentSamples / sampleRate) * 1000);
}
